### PR TITLE
Related to HBA-38

### PR DESCRIPTION
**Pull request by Iasmina2001**
I added a view for the hotel manager, where he can edit his hotel data.

### CODE REVIEW

**Comment by BalloonW** [comment]
What happens if you don't introduce some data?

**Comment by Iasmina2001** [comment]
The data remains unmodified.

**Comment by Iasmina2001** [comment]
> What happens if you don't introduce some data?

The data remains unmodified.

**Comment by BalloonW** [comment]
> > What happens if you don't introduce some data?
> 
> The data remains unmodified.

Ok, so it's good then.

**Review by BalloonW — APPROVED** [review]
looks fine

**Pull request merged**
